export const buildBicepContent = ({
  appName,
  selectedEnv,
  location,
  resourceGroupName,
  configuredComponents
}) => {
  if (!appName || !location || !Array.isArray(configuredComponents) || configuredComponents.length === 0) {
    throw new Error('Información insuficiente para generar el Bicep. Verifica que exista al menos un componente configurado y los datos básicos.');
  }

  const now = new Date()
  const formattedDate = now.toLocaleString('es-ES', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })

  let content = ''
  const append = (line = '') => {
    content += line + '\n'
  }

  append('targetScope = \'subscription\'')
  append()
  append('// ============================================================================')
  append(`//  AppName: ${appName}`)
  append(`//  ResourceGroup: ${resourceGroupName || ''}`)
  append(`//  Location: ${location}`)
  append(`//  Environment: ${selectedEnv}`)
  append('//  Generated by: InfraGen v1.0')
  append(`//  Created: ${formattedDate}`)
  append('// ============================================================================')
  append()

  append('// Parámetros de la infraestructura')
  append("@description('Nombre de la aplicación')")
  append(`param appName string = '${appName}'`)
  append()
  append("@description('Ambiente de despliegue')")
  append(`param environment string = '${selectedEnv}'`)
  append()
  append("@description('Ubicación de los recursos')")
  append(`param location string = '${location}'`)
  append()
  append("@description('Nombre del Resource Group')")
  append(`param resourceGroupName string = '${resourceGroupName || ''}'`)
  append()
  append("@description('Tags comunes para todos los recursos')")
  append('param tags object = {')
  append('  project: appName')
  append('  environment: environment')
  append('  location: location')
  append('}')
  append()
  append('param componentTags object = {}')
  append()

  append('// Resource Group')
  append(`resource rg 'Microsoft.Resources/resourceGroups@2021-04-01' = {`)
  append('  name: resourceGroupName')
  append('  location: location')
  append('  tags: tags')
  append('}')
  append()

  configuredComponents.forEach((item) => {
    const cfg = item.config || {}

    if (item.value === 'StorageAccount') {
      if (!cfg.name) throw new Error('StorageAccount configuration is missing a name')
      append(`// Storage Account ${cfg.name}`)
      append(`resource storageAccount_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Storage/storageAccounts@2023-01-01' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append('  sku: {')
      append(`    name: '${cfg.sku || 'Standard_LRS'}'`)
      append(`    tier: '${cfg.tier || 'Standard'}'`)
      append('  }')
      append(`  kind: '${cfg.kind || 'StorageV2'}'`)
      append('  properties: {')
      append(`    allowBlobPublicAccess: ${cfg.enableBlobPublicAccess || false}`)
      append(`    supportsHttpsTrafficOnly: ${cfg.httpsOnly !== undefined ? cfg.httpsOnly : true}`)
      if (cfg.accessTier) {
        append(`    accessTier: '${cfg.accessTier}'`)
      }
      append('  }')
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'AppServicePlan') {
      if (!cfg.name) throw new Error('AppServicePlan configuration is missing a name')
      append(`// App Service Plan ${cfg.name}`)
      append(`resource appServicePlan_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Web/serverfarms@2023-06-01' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append('  sku: {')
      append(`    name: '${cfg.sku || 'P1v2'}'`)
      append(`    tier: '${cfg.tier || 'PremiumV2'}'`)
      append('  }')
      append(`  kind: '${cfg.os === 'Linux' ? 'linux' : 'windows'}'`)
      if (cfg.perSiteScaling !== undefined) {
        append('  properties: {')
        append(`    perSiteScaling: ${cfg.perSiteScaling}`)
        append('  }')
      }
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'AppService') {
      if (!cfg.name) throw new Error('AppService configuration is missing a name')
      append(`// App Service ${cfg.name}`)
      append(`resource appService_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Web/sites@2023-02-01' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      if (cfg.appServicePlan) {
        append('  properties: {')
        append(`    serverFarmId: appServicePlan_${cfg.appServicePlan.replace(/[^a-zA-Z0-9]/g, '')}.id`)
        append('  }')
      }
      if (cfg.httpsOnly !== undefined) {
        append(`  httpsOnly: ${cfg.httpsOnly}`)
      }
      if (cfg.netFrameworkVersion) {
        append(`  netFrameworkVersion: '${cfg.netFrameworkVersion}'`)
      }
      if (cfg.linuxFxVersion) {
        append(`  linuxFxVersion: '${cfg.linuxFxVersion}'`)
      }
      if (cfg.minTlsVersion) {
        append(`  minTlsVersion: '${cfg.minTlsVersion}'`)
      }
      if (cfg.ftpsState) {
        append(`  ftpsState: '${cfg.ftpsState}'`)
      }
      if (cfg.appSettings && cfg.appSettings.length > 0) {
        append('  properties: {')
        append('    siteConfig: {')
        append('      appSettings: [')
        cfg.appSettings.forEach(setting => {
          if (setting.name && setting.value) {
            append(`        { name: '${setting.name}' value: '${setting.value}' }`)
          }
        })
        append('      ]')
        append('    }')
        append('  }')
      }
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'SQLServer') {
      if (!cfg.name) throw new Error('SQLServer configuration is missing a name')
      append(`// SQL Server ${cfg.name}`)
      append(`resource sqlServer_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Sql/servers@2023-02-01' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append('  properties: {')
      append(`    administratorLogin: '${cfg.adminUsername || 'sqladmin'}'`)
      append(`    administratorLoginPassword: '${cfg.adminPassword || 'P@ssw0rd123!'}'`)
      append(`    version: '${cfg.version || '12.0'}'`)
      append(`    minimalTlsVersion: '${cfg.minimalTlsVersion || '1.2'}'`)
      append(`    publicNetworkAccess: '${cfg.publicNetworkAccess || 'Enabled'}'`)
      append('  }')
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'SQLDatabase') {
      if (!cfg.name) throw new Error('SQLDatabase configuration is missing a name')
      append(`// SQL Database ${cfg.name}`)
      append(`resource sqlDatabase_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Sql/servers/databases@2023-02-01' = {`)
      if (cfg.sqlServer) {
        append(`  parent: sqlServer_${cfg.sqlServer.replace(/[^a-zA-Z0-9]/g, '')}`)
      }
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append('  sku: {')
      append(`    name: '${cfg.sku || 'Basic'}'`)
      append(`    tier: '${cfg.tier || 'Basic'}'`)
      if (cfg.capacity) {
        append(`    capacity: ${cfg.capacity}`)
      }
      append('  }')
      append('  properties: {')
      if (cfg.collation) {
        append(`    collation: '${cfg.collation}'`)
      }
      if (cfg.maxSizeBytes) {
        append(`    maxSizeBytes: ${cfg.maxSizeBytes}`)
      }
      if (cfg.readScale) {
        append(`    readScale: '${cfg.readScale}'`)
      }
      if (cfg.zoneRedundant !== undefined) {
        append(`    zoneRedundant: ${cfg.zoneRedundant}`)
      }
      if (cfg.enableThreatDetection !== undefined) {
        append('    threatDetectionSettings: {')
        append(`      state: '${cfg.enableThreatDetection ? 'Enabled' : 'Disabled'}'`)
        append('    }')
      }
      append('  }')
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'ContainerApp') {
      if (!cfg.name) throw new Error('ContainerApp configuration is missing a name')
      const envName = cfg.containerAppEnvironment || `${appName}-${selectedEnv}-cae`
      append(`// Container Apps Environment ${envName}`)
      append(`resource containerAppEnvironment_${envName.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.App/managedEnvironments@2023-05-01' = {`)
      append('  scope: rg')
      append(`  name: '${envName}'`)
      append('  location: location')
      append('  properties: {')
      append('    zoneRedundant: false')
      append('  }')
      append('  tags: tags')
      append('}')
      append()
      append(`// Container App ${cfg.name}`)
      append(`resource containerApp_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.App/containerApps@2023-05-01' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append('  dependsOn: [')
      append(`    containerAppEnvironment_${envName.replace(/[^a-zA-Z0-9]/g, '')}`)
      append('  ]')
      append('  properties: {')
      append(`    managedEnvironmentId: containerAppEnvironment_${envName.replace(/[^a-zA-Z0-9]/g, '')}.id`)
      append('    configuration: {')
      if (cfg.enableIngress) {
        append('      ingress: {')
        append('        external: true')
        append(`        targetPort: ${cfg.targetPort || 80}`)
        append(`        allowInsecure: ${cfg.allowInsecure || false}`)
        append('        traffic: [')
        append('          {')
        append('            weight: 100')
        append('            latestRevision: true')
        append('          }')
        append('        ]')
        append('      }')
      }
      append('      secrets: []')
      append('    }')
      append('    template: {')
      append('      containers: [')
      append('        {')
      append(`          name: '${cfg.name.toLowerCase().replace(/[^a-z0-9-]/g, '-')}'`)
      append(`          image: '${cfg.containerImage || 'ubuntu:latest'}'`)
      append('          resources: {')
      append(`            cpu: ${cfg.cpu || '0.25'}`)
      append(`            memory: '${cfg.memory || '0.5Gi'}'`)
      append('          }')
      if (cfg.environmentVariables && cfg.environmentVariables.length > 0) {
        append('          env: [')
        cfg.environmentVariables.forEach(envVar => {
          if (envVar.name && envVar.value) {
            append('            {')
            append(`              name: '${envVar.name}'`)
            append(`              value: '${envVar.value}'`)
            append('            }')
          }
        })
        append('          ]')
      }
      append('        }')
      append('      ]')
      append('      scale: {')
      append(`        minReplicas: ${cfg.minReplicas || 0}`)
      append(`        maxReplicas: ${cfg.maxReplicas || 10}`)
      append('      }')
      append('    }')
      append('  }')
      append('  tags: tags')
      append('}')
      append()
      return
    }

    if (item.value === 'MonitoringAlerts') {
      if (!cfg.name) throw new Error('MonitoringAlerts configuration is missing a name')
      append(`// Application Insights ${cfg.name}`)
      append(`resource applicationInsights_${cfg.name.replace(/[^a-zA-Z0-9]/g, '')} 'Microsoft.Insights/components@2020-02-02' = {`)
      append('  scope: rg')
      append(`  name: '${cfg.name}'`)
      append('  location: location')
      append("  kind: 'web'")
      append('  properties: {')
      append(`    Application_Type: 'web'`)
      append(`    publicNetworkAccessForIngestion: '${cfg.publicNetworkAccessForIngestion || 'Enabled'}'`)
      append(`    publicNetworkAccessForQuery: '${cfg.publicNetworkAccessForQuery || 'Enabled'}'`)
      append('  }')
      append('  tags: tags')
      append('}')
      append()
    }
  })

  return content
}
